//
// Generated by JTB 1.2.2
//

package org.postgresql.stado.parser.core.syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <STAR_> | <DIVIDE_> | <MOD_> | <DIV_> | <MODULO_> | <AND_BITWISE_> | <OR_BITWISE_> | <XOR_BITWISE_> | <SHIFT_LEFT_BITWISE_> | <SHIFT_RIGHT_BITWISE_> | <CONTAINED_WITHIN_OR_EQUALS_> | <CONTAINS_OR_EQUALS_> | <GREATER_> | <GREATER_EQUALS_> | <LESS_> | <LESS_EQUALS_> | <EQUALS_> | <NOT_EQUALS_> | <NOT_EQUALS_2_> | <GIS_OVERLAPS_> | <GIS_OVERLAPS_RIGHT_> | <GIS_OVERLAPS_LEFT_> | <GIS_OVERLAPS_BELOW_> | <GIS_OVERLAPS_ABOVE_> | <GIS_SAME_> | <GIS_STRICT_BELOW_> | <GIS_STRICT_ABOVE_> | <NOT_BITWISE_> | <ABSOLUTE_> )
 * f1 -> SQLPrimaryExpression(prn)
 */
public class SQLMultiplicativeExpressionOperand implements Node {
   public NodeChoice f0;
   public SQLPrimaryExpression f1;

   public SQLMultiplicativeExpressionOperand(NodeChoice n0, SQLPrimaryExpression n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.postgresql.stado.parser.core.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(org.postgresql.stado.parser.core.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

